apiVersion: v1
kind: Secret
metadata:
  namespace: harness-agent # same namespace of argocd-app
  name: {{.Values.cluster_name}}
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: new-eks # Get from clusters - name field in config k8s file.
  project: 56b2aff2
  server: {{.Values.cluster_endpoint}} 
  config: |
    {
      "bearerToken": "{{.Values.bearer_token}}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "{{.Values.ca_cert}}"
      }
    }
